<?php

if (!defined('BASEPATH'))
exit('No direct script access allowed');

class Permendagri_model extends CI_Model
{

    public $table = 'permendagri';
    public $id = 'id_nya';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get urusan
    function get_urusan() {
        $this->db->select('*');
        $this->db->where('p_id', null);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_nya', $q);
	$this->db->or_like('Kode', $q);
	$this->db->or_like('Bidang_Urusan_Program_Kegiatan_Sub_Kegiatan', $q);
	$this->db->or_like('Kinerja', $q);
	$this->db->or_like('Indikator', $q);
	$this->db->or_like('Satuan', $q);
	$this->db->or_like('p_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_nya', $q);
	$this->db->or_like('Kode', $q);
	$this->db->or_like('Bidang_Urusan_Program_Kegiatan_Sub_Kegiatan', $q);
	$this->db->or_like('Kinerja', $q);
	$this->db->or_like('Indikator', $q);
	$this->db->or_like('Satuan', $q);
	$this->db->or_like('p_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Permendagri_model.php */
/* Location: ./application/models/Permendagri_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-01-31 15:43:26 */
/* http://harviacode.com */