<?php

if (!defined('BASEPATH'))
exit('No direct script access allowed');

class Bidang_add_model extends CI_Model
{

    public $table = 'bidang_add';
    public $id = 'id_ba';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by('kode_bidang', $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_bid_ad()
    {
        $this->db->order_by('kode_bidang', $this->order);
        $abc = $this->db->get($this->table)->result();
        $hsl = array();
        foreach ($abc as $a) {
            $hsl[] = $a->kode_bidang;
        }
        return $hsl;
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_ba', $q);
	$this->db->or_like('nama_bidang', $q);
	$this->db->or_like('kode_bidang', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_ba', $q);
	$this->db->or_like('nama_bidang', $q);
	$this->db->or_like('kode_bidang', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Bidang_add_model.php */
/* Location: ./application/models/Bidang_add_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-01-31 14:50:34 */
/* http://harviacode.com */