<?php

if (!defined('BASEPATH'))
exit('No direct script access allowed');

class Rekomendasi_model extends CI_Model
{

    public $table = 'rekomendasi';
    public $id = 'id_rek';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function get_urusan($id_user) {

        $this->db->select('*');
        $this->db->from('rekomendasi_urusan');
        $this->db->order_by('kode');
        $this->db->group_by('kode');

        $parent = $this->db->get();
        
        $categories = $parent->result();
        
        $i=0;
        foreach($categories as $p_cat){

            $categories[$i]->sub = $this->get_opd($p_cat->id_rek_urusan);
            $i++;
        }
        return $categories;
    }


    public function get_opd($id) {
        $con = array('p_id' => $id, 'tahun' => $this->session->userdata('ta'));
        $this->db->select('id_rek_opd, tahun, kode, nama_user, id_user');
        $this->db->from('rekomendasi_opd');
        $this->db->join('user', 'user.id_user=rekomendasi_opd.opd');
        $this->db->where($con);

        $parent = $this->db->get();
        
        $categories = $parent->result();
        
        $i=0;
        foreach($categories as $p_cat){

            $categories[$i]->sub = $this->get_rekomendasi($p_cat->id_rek_opd);
            $i++;
        }
        return $categories;
    }

    public function get_rekomendasi($id) {
        $con = array('p_id' => $id);
        $this->db->select('*');
        $this->db->from('rekomendasi');
        $this->db->where($con);

        $parent = $this->db->get();
        
        $categories = $parent->result();
        
        return $categories;
    }

    public function check_urusan($id) {
        $con = array('opd_id' => $id);
        $this->db->select('p_id, opd_id, nmBid, kdUrus, nmUrus');
        $this->db->from('bidang');
        $this->db->join('urusan', 'bidang.p_id=urusan.kdUrus');
        $this->db->where($con);

        $parent = $this->db->get();
        
        $categories = $parent->result();
        return $categories;
    }

    public function save_rekomendasi_urusan($data) {
        $check = $this->check_kode_urusan($data['kode']); 
        if(isset($check)) {
            return $check;
        } else {
            $this->db->insert('rekomendasi_urusan', $data);
            $insert_id = $this->db->insert_id();
            return  $insert_id;
        }
    }

    public function check_kode_urusan($kode) {
        
        $this->db->where('kode', $kode);
        $query = $this->db->get('rekomendasi_urusan');
        if ($query->num_rows() > 0) {
            return $kode; // ID ditemukan, mengembalikan ID
        } else {
            return null; // ID tidak ditemukan, mengembalikan false
        }

    }

    public function save_rekomendasi_opd($data) {

        $get = $this->check_kode_opd($data['opd']);

        if(isset($get)) {
            return $get;
        } else {
            $this->db->insert('rekomendasi_opd', $data);
            $insert_id = $this->db->insert_id();
            return  $insert_id;
        }
    }

    public function check_kode_opd($opd) {
        
        $this->db->where('opd', $opd);
        $query = $this->db->get('rekomendasi_opd');

        if ($query->num_rows() > 0) {
            return $query->row()->id_rek_opd; ; // ID ditemukan, mengembalikan ID
        } else {
            return null; // ID tidak ditemukan, mengembalikan false
        }

    }


}

/* End of file Rekomendasi_model.php */
/* Location: ./application/models/Rekomendasi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-02-10 23:32:32 */
/* http://harviacode.com */