<?php

if (!defined('BASEPATH'))
exit('No direct script access allowed');

class Penjadwalan extends CI_Controller
{
    function __construct() {
        parent::__construct();
        $this->load->model(array('Penjadwalan_model', 'user/User_model'));
        $this->load->library(array('form_validation', 'Jadwal'));
        $this->jadwal->check_jadwal();
    }

    public function index()
        {
            $data_opd = $this->User_model->get_user_ar();
            $q = urldecode($this->input->get('q', TRUE));
            $start = intval($this->input->get('start'));

            if ($q <> '') {
                $config['base_url'] = base_url() . 'penjadwalan/index.html?q=' . urlencode($q);
                $config['first_url'] = base_url() . 'penjadwalan/index.html?q=' . urlencode($q);
                } else {
                    $config['base_url'] = base_url() . 'penjadwalan/index.html';
                    $config['first_url'] = base_url() . 'penjadwalan/index.html';
                }

                $config['per_page'] = 10;
                $config['page_query_string'] = TRUE;
                $config['total_rows'] = $this->Penjadwalan_model->total_rows($q);
                $penjadwalan = $this->Penjadwalan_model->get_limit_data($config['per_page'], $start, $q);

                $this->load->library('pagination');
                $this->pagination->initialize($config);

                $data = array(
                'penjadwalan_data' => $penjadwalan,
                'opd' => $data_opd,
                'q' => $q,
                'pagination' => $this->pagination->create_links(),
                'total_rows' => $config['total_rows'],
                'start' => $start,
                );

                $data['judul'] = 'Data Penjadwalan';

                $this->load->view('templates/header', $data);
                $this->load->view('penjadwalan/penjadwalan_list', $data);
                $this->load->view('templates/footer', $data);
            }


            public function save_jadwal() {
                $date_mulai = $this->input->post('date_mulai',TRUE);
                $time_mulai = $this->input->post('time_mulai',TRUE);

                $date_selesai = $this->input->post('date_selesai',TRUE);
                $time_selesai = $this->input->post('time_selesai',TRUE);

                // Konversi format tanggal dan waktu ke dalam format datetime MySQL
                $date_mulai_gab = $date_mulai . ' ' . $time_mulai; // Gabungkan tanggal dan waktu
                $date_selesai_gab = $date_selesai . ' ' . $time_selesai; // Gabungkan tanggal dan waktu
                $dmulai = date('Y-m-d H:i:s', strtotime($date_mulai_gab));
                $dselesai = date('Y-m-d H:i:s', strtotime($date_selesai_gab));

                $data = array(
            		'tgl_mulai' => $dmulai,
            		'tgl_selesai' => $dselesai,
                    'tahun' => $this->input->post('tahun'),
                );

                $this->Penjadwalan_model->insert($data);
                $this->session->set_flashdata('success', 'Ditambah');
                redirect($_SERVER['HTTP_REFERER']);
            }

            public function set_status($id, $val) {

                $this->User_model->update_status($id , $val);

                if($val == 1) {
                    $this->session->set_flashdata('success', 'Dibuka');
                } else {
                    $this->session->set_flashdata('success', 'Ditutup');
                }
                redirect($_SERVER['HTTP_REFERER']);
            }


            public function delete($id) 
            {
                $row = $this->Penjadwalan_model->get_by_id($id);

                if ($row) {
                    $this->Penjadwalan_model->delete($id);
                    $this->session->set_flashdata('success', 'Dihapus');
                    redirect(site_url('penjadwalan'));
                    } else {
                        $this->session->set_flashdata('error', 'Data tidak ditemukan');
                        redirect(site_url('penjadwalan'));
                    }
            }

}

/* End of file Penjadwalan.php */
                        /* Location: ./application/controllers/Penjadwalan.php */
                        /* Please DO NOT modify this information : */
                        /* Generated by Harviacode Codeigniter CRUD Generator 2024-01-26 14:12:49 */
                        /* http://harviacode.com */